### PR TITLE
Connect lasso log messages to mellon's logging

### PR DESCRIPTION
**Pull request by jdennis**
Mellon utilizes the Lasso library for most of it's SAML
operations. Therefore access to Lasso's log messages are often useful
when diagnosing SAML issues. This patch adds a logging callback
handler that is passed into Lasso. When Lasso emits a message the
callback handler is invoked. The Lasso log level is translated to a
Apache log level, tagged with Lasso's log domain and then emitted as a
message from the mellon module.

Signed-off-by: John Dennis <jdennis@redhat.com>

### CODE REVIEW

**Comment by olavmrk** [comment]
Hi,

I think this will need some sort of feature test, since this requires a reasonably recent version of the Lasso library. At least, that is what I assume based on the Travis CI output.

**Comment by jdennis** [comment]
OK, I can do that. Is there a way for me to run the Travis CI before I submit a pull request so I make sure everything is good?

**Comment by jdennis** [comment]
Hmm... lasso_log_handler was added 8 years ago to Lasso, first appearing in lasso 2.3.0. 

commit 4c130d779aff0d043c17c1087180af64d5288cf4
Author: Frederic Peters <fpeters@entrouvert.com>
Date:   Wed Jun 9 07:51:52 2010 +0000

It first appeared in a public header file (xml/tools.h) 7 years ago,  10 months later in lasso 2.4.0
commit 95f48822f41eede822bbc46a64aedcf1adee6dc7
Author: Benjamin Dauvergne <bdauvergne@entrouvert.com>
Date:   Thu Apr 14 17:12:29 2011 +0200

xml/tools.h is included by utils.h, in commit a9b673cd4 first appearing in lasso 2.3.0

Hence as far as I can figure out lasso_log_handler would have been public as of lasso 2.4.0 and would have resolved via this Mellon include in lasso_compat.h

#ifdef HAVE_LASSO_UTILS_H
#include <lasso/utils.h>

How far back are we committed to supporting? I'm happy to add the feature test, but given this symbol should have been visible for the last 7 years I'm wondering if something else is amiss.

Looking at the configure output in the Travis job I see this:

checking lasso/utils.h usability... no
checking lasso/utils.h presence... no
checking for lasso/utils.h... no

So for some reason on this system lasso/utils.h is not present. Why? What I couldn't find in the Travis output is the version of Lasso. Do you know what version it is? Can it really be more than 7 years old?

I seem recall some issue with Debian where they didn't package lasso/utils.h, but my memory is fuzzy.

Rather than a feature test I'm more included to add the prototype to lasso_compat.h in the part of the header where HAVE_LASSO_UTILS_H is false. My vague memory is we had to do this for other things, hence the whole purpose of lasso_compat.h

**Comment by jdennis** [comment]
Ah, I found the lasso version in Travis output, I just didn't know where to look at first

Preparing to unpack .../liblasso3_2.4.0-2build1_amd64.deb

So I'm guessing this is a Debian packaging problem where they didn't include all the header files in the deb package that Lasso 2.4.0 exported.

**Comment by thijskh** [comment]
Well, travis uses Ubuntu Trusty which is indeed 4 years old. However, it looks to me that the trusty lasso3-dev package does include utils.h? Sure it's a packaging problem? https://packages.ubuntu.com/trusty/amd64/liblasso3-dev/filelist

**Comment by jdennis** [comment]
> Well, travis uses Ubuntu Trusty which is indeed 4 years old. However, it looks to me that the trusty lasso3-dev package does include utils.h? Sure it's a packaging problem? https://packages.ubuntu.com/trusty/amd64/liblasso3-dev/filelist

Beats me, all I know is the configure script can't find it based on the captured output from the Travis run

> checking for lasso/utils.h... no

Maybe it's a bug in autotools or configure.ac, but not having access to this environment makes it difficult for me to diagnose why it's not finding the header file.

**Comment by olavmrk** [comment]
The Travis build environment is indeed ancient. They have not yet shipped 16.04, and by this time 18.04 is the new LTS.

> Maybe it's a bug in autotools or configure.ac, but not having access to this environment makes it difficult for me to diagnose why it's not finding the header file.

The simplest way is usually to use Docker. Something like this in a `Dockerfile` should work:

```
FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install --no-install-recommends -y \
  apache2-dev \
  automake \
  gcc \
  libcurl4-openssl-dev \
  libglib2.0-dev \
  liblasso3-dev \
  libssl-dev
COPY . /mod_auth_mellon
WORKDIR /mod_auth_mellon
RUN ./autogen.sh
RUN ./configure
RUN make
```

To diagnose build issues, drop the three last `RUN`-lines, start a container and run the build commands manually.

In any case, I see you have fixed the build failure -- does that mean that this patch is ready to merge?

**Comment by bufferoverflow** [comment]
This would be a good addition!

**Comment by olavmrk** [comment]
Closing this pull request as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md

**Pull request closed without merging**
